import TopHeader from "@/components/Common/Header/TopHeader";
import { Barlow_Semi_Condensed, Nunito } from "next/font/google";
import "./globals.css";

const barlow_Semi_Condensed = Barlow_Semi_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

const nunito = Nunito({
  weight: ["200", "300", "400", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlow_Semi_Condensed.className} ${nunito.className}`}
      >
        <TopHeader />
        {children}
      </body>
    </html>
  );
}
